[build]
  publish = "war-tracker/war-tracker"
  command = ""
  functions = "war-tracker/war-tracker/netlify/functions"

# Redirect rules
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
